server:
  port: 8096
springdoc:
  api-doc:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/automotriz
    username: root
    password:
