server:
  port: 8086
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cocina
    username: root
    password:
